#!/usr/bin/env python3
"""Maintainer tool: pin the exact wheels (URL + SHA-256) the panel downloads for its Python dependencies.

Run after changing VERSIONS; it rewrites integrations/dependency_lock.py. Installed panels only ever
download files listed there and verify each SHA-256 before extracting.
"""
import json
from pathlib import Path
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
PYTHONS = ('310', '311', '312', '313', '314')
# cryptography dropped Intel macOS wheels in 49.0; Intel Macs stay on the last release that has them.
PLATFORMS = {
    'linux-x86_64': ('50.0.2', ('manylinux2014_x86_64',)),
    'linux-aarch64': ('50.0.2', ('manylinux2014_aarch64',)),
    'darwin-arm64': ('50.0.2', ('macosx_11_0_arm64', 'universal2')),
    'darwin-x86_64': ('48.0.1', ('x86_64', 'universal2')),
}
CFFI, PYCPARSER, TYPING = '2.1.1', '3.0', '4.15.0'


def release(name, version):
    with urllib.request.urlopen(f'https://pypi.org/pypi/{name}/{version}/json', timeout=60) as response:
        return [f for f in json.load(response)['urls'] if f['filename'].endswith('.whl') and not f.get('yanked')]


def pick(files, *needles):
    for item in files:
        if all(n in item['filename'] for n in needles):
            return entry(item)
    raise SystemExit('No wheel matches ' + ' '.join(needles))


def entry(item):
    return {'filename': item['filename'], 'url': item['url'], 'sha256': item['digests']['sha256']}


def pick_platform(files, tag, platforms):
    for platform in platforms:
        for item in files:
            if tag in item['filename'] and platform in item['filename']:
                return entry(item)
    raise SystemExit(f'No wheel for {tag} {platforms}')


def stable_abi(files, platforms):
    """The abi3 wheel with the newest minimum Python that still runs on 3.10."""
    usable = []
    for item in files:
        name = item['filename']
        if '-abi3-' in name and int(name.split('-')[2][2:]) <= 310:
            usable.append(item)
    usable.sort(key=lambda item: -int(item['filename'].split('-')[2][2:]))
    return pick_platform(usable, '-abi3-', platforms)


def main():
    cffi, pycparser, typing = release('cffi', CFFI), release('pycparser', PYCPARSER), release('typing-extensions', TYPING)
    lock = {}
    for key, (version, platforms) in PLATFORMS.items():
        crypto = release('cryptography', version)
        system = key.split('-')[0]
        crypto_file = stable_abi([f for f in crypto if ('macosx' in f['filename']) == (system == 'darwin')], platforms)
        for python in PYTHONS:
            cffi_files = [f for f in cffi if f'-cp{python}-cp{python}-' in f['filename'] and ('macosx' in f['filename']) == (system == 'darwin')]
            wheels = [crypto_file, pick_platform(cffi_files, f'cp{python}', platforms if system == 'linux' else ('arm64',) if key.endswith('arm64') else ('x86_64',)), pick(pycparser, 'py3-none-any')]
            if python == '310':
                wheels.append(pick(typing, 'py3-none-any'))
            lock[f'cp{python}-{key}'] = wheels
    body = json.dumps(lock, indent=1, sort_keys=True)
    (ROOT / 'integrations/dependency_lock.py').write_text(
        '"""Generated by scripts/lock-dependencies.py; do not edit by hand."""\n'
        f'CRYPTOGRAPHY = {json.dumps({k: v[0] for k, v in PLATFORMS.items()}, sort_keys=True)}\n'
        f'WHEELS = {body}\n')
    print(f'{len(lock)} platform/Python combinations pinned')


if __name__ == '__main__':
    main()
